name: easy_quiz_game
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  provider: ^6.0.5
  collection: ^1.17.0
  shared_preferences: ^2.0.17
  audioplayers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  assets:
    - assets/
    - assets/images/
    - assets/sounds/